services:
  - type: web
    name: student-management-backend
    env: java
    buildCommand: chmod +x mvnw && ./mvnw clean install
    startCommand: java -jar target/student-management-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/java
